name: ev_server
dependencies:
  args: ">=0.10.0 <0.11.0"
  logging: ">=0.9.2 <0.10.0"
  credit_cat: ">=0.2.4 <0.3.0"
  dart_config: ">=0.5.0 <0.6.0"
  mustache4dart: ">=1.0.7 <2.0.0"
  mongo_dart: ">=0.1.45 <0.2.0"
  shelf: ">=0.5.5+1 <0.6.0"
  shelf_route: ">=0.10.1 <0.11.0"
  shelf_proxy: ">=0.1.0+1 <0.2.0"
  shelf_bind: ">=0.7.0 <0.8.0"
  shelf_rest: ">=0.1.3+1 <0.2.0"
  shelf_static: ">=0.2.1 <0.3.0"
  ev_common:
    path: ../ev_common
  ev_client:
    path: ../ev_client